### ISSUE TITLE
IOException when closing the browser tab

### ISSUE THREAD

**Issue by uyilmaz** [mslosarz/nextrtc-example-videochat#13]
After I leave a room and close the browser tab those exceptions occur:

`java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_121]
        at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_121]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_121]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_121]
        at org.apache.tomcat.util.net.SecureNioChannel.flush(SecureNioChannel.java:143) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.util.net.SecureNioChannel.close(SecureNioChannel.java:479) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.close(NioEndpoint.java:1185) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doClose(WsRemoteEndpointImplServer.java:171) ~[tomcat-embed-websocket-8.5.4.j
ar!/:8.5.4]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.close(WsRemoteEndpointImplBase.java:710) [tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.websocket.WsSession.sendCloseMessage(WsSession.java:613) [tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:526) [tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.websocket.WsFrameBase.processDataControl(WsFrameBase.java:348) [tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:290) [tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131) [tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:69) [tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-embed-websocket-8.5.4.jar!/:
8.5.4]
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_121]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]`

I'm guessing it's not a bug but it fills up the logs anyways.

**Comment by mslosarz** [comment]
This issue was fixed in 0.0.6 version
