### ISSUE TITLE
RC5 version does NOT exist in maven repository

### ISSUE THREAD

**Issue by WilsonHu** [mslosarz/nextrtc-example-videochat#23]
[WARNING] The POM for org.nextrtc.signalingserver:nextrtc-signaling-server:jar:1.0.0-RC5 is missing, no dependency information available.

The latest version is RC4

**Comment by mslosarz** [comment]
Hello, That's true I'm going to deploy latest RC5 version, but I need to describe changes, and how to migrate to latest version.

**Comment by mslosarz** [comment]
you can build for just for now RC5 from the source https://github.com/mslosarz/nextrtc-signaling-server, I apologize for the inconvenience.

**Comment by WilsonHu** [comment]
Hey, Mslasarz. Please don't say sorry about that, what you are doing is amazing.
I have packaged RC5's jar and added it as a library to the sample project. I meet another error about @Inject missing.
Maybe the **javax.inject** dependency is needed.

**Comment by mslosarz** [comment]
That's why I didn't release it yet :) I'll push my changes to all 3 sample
project then you'll be able to test it

śr., 4.07.2018, 18:33 użytkownik Wilson.Hu <notifications@github.com>
napisał:

**Comment by mslosarz** [comment]
Please try rebuild it now. You shouldn't have any issue with @Inject because it's supported by Spring, but I've replaced this annotation with @Autowired.

**Comment by WilsonHu** [comment]
Hey, Mslasarz. Thank you so much for the reply.
Currently, I build RC5 successfully and add it as a library for "nextrtc-example-videochat". When I try to run  the demo via IntelliJ, I got an error as below:
=================================================================
2018-07-05 23:44:43.393 ERROR 4712 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name '**nextRTCEventBus**' defined in org.nextrtc.signalingserver.NextRTCConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.nextrtc.signalingserver.api.NextRTCEventBus]: Factory method 'eventBus' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/eventbus/EventBus
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.nextrtc.examples.videochat.SampleWebStaticApplication.main(SampleWebStaticApplication.java:16) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.nextrtc.signalingserver.api.NextRTCEventBus]: Factory method 'eventBus' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/eventbus/EventBus
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/google/common/eventbus/EventBus
	at org.nextrtc.signalingserver.api.NextRTCEventBus.<init>(NextRTCEventBus.java:17) ~[nextrtc-signaling-server-1.0.0-RC5.jar:na]
	at org.nextrtc.signalingserver.NextRTCConfig.eventBus(NextRTCConfig.java:24) ~[nextrtc-signaling-server-1.0.0-RC5.jar:na]
	at org.nextrtc.signalingserver.NextRTCConfig$$EnhancerBySpringCGLIB$$cad56f6b.CGLIB$eventBus$1(<generated>) ~[nextrtc-signaling-server-1.0.0-RC5.jar:na]
	at org.nextrtc.signalingserver.NextRTCConfig$$EnhancerBySpringCGLIB$$cad56f6b$$FastClassBySpringCGLIB$$be2dca4f.invoke(<generated>) ~[nextrtc-signaling-server-1.0.0-RC5.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.nextrtc.signalingserver.NextRTCConfig$$EnhancerBySpringCGLIB$$cad56f6b.eventBus(<generated>) ~[nextrtc-signaling-server-1.0.0-RC5.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.eventbus.EventBus
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_172]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_172]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_172]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_172]
	... 31 common frames omitted

Process finished with exit code 1
============================================================
And when I try to compile the demo project, got an error that cannot find package "org.nextrtc.signalingserver.api", I am afraid that maybe the JAR importing has a problem.

Jestem nowicjuszem, proszę, wybacz mi.

**Comment by WilsonHu** [comment]
To demonstrate quickly, I switch the signaling library from RC5 to RC4  in pom.xml. It works for me.
Thank you!

**Comment by mslosarz** [comment]
I've released version RC5. So please remove your local build (remove directory with RC5 from {maven directory usually ~/.m2}/repository/org/nextrtc/signalingserver/nextrtc-signaling-server/). Please checkout latest version of example-videochat (there are changes, that breaks backward compatibility), and run command from Readme. This time it should build and run without any errors :)
